import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';
import { Colors } from './Colors';

export const PaperLightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: Colors.light.primary,
    onPrimary: Colors.light.text,
    primaryContainer: Colors.light.accent,
    onPrimaryContainer: Colors.light.text,
    secondary: Colors.light.headerBackground,
    onSecondary: Colors.light.headerText,
    secondaryContainer: '#E9DEBB', // Light gold shade
    onSecondaryContainer: Colors.light.text,
    tertiary: '#5A5A5A',
    onTertiary: Colors.light.background,
    tertiaryContainer: '#DDDDDD',
    onTertiaryContainer: Colors.light.text,
    error: Colors.light.error,
    onError: Colors.light.background,
    errorContainer: '#FFCDD2',
    onErrorContainer: Colors.light.text,
    background: Colors.light.background,
    onBackground: Colors.light.text,
    surface: Colors.light.background,
    onSurface: Colors.light.text,
    surfaceVariant: Colors.light.cardBackground,
    onSurfaceVariant: Colors.light.text,
    outline: '#DDDDDD',
    elevation: {
      level0: 'transparent',
      level1: '#F5F5F5',
      level2: '#EEEEEE',
      level3: '#E0E0E0',
      level4: '#D6D6D6',
      level5: '#C2C2C2',
    },
  },
};

export const PaperDarkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: Colors.dark.primary,
    onPrimary: Colors.dark.background,
    primaryContainer: Colors.dark.accent,
    onPrimaryContainer: Colors.dark.text,
    secondary: Colors.dark.headerBackground,
    onSecondary: Colors.dark.headerText,
    secondaryContainer: '#3D3D3D',
    onSecondaryContainer: Colors.dark.text,
    tertiary: '#9E9E9E',
    onTertiary: Colors.dark.background,
    tertiaryContainer: '#5A5A5A',
    onTertiaryContainer: Colors.dark.text,
    error: Colors.dark.error,
    onError: Colors.dark.background,
    errorContainer: '#B71C1C',
    onErrorContainer: Colors.dark.text,
    background: Colors.dark.background,
    onBackground: Colors.dark.text,
    surface: Colors.dark.background,
    onSurface: Colors.dark.text,
    surfaceVariant: Colors.dark.cardBackground,
    onSurfaceVariant: Colors.dark.text,
    outline: '#5A5A5A',
    elevation: {
      level0: 'transparent',
      level1: '#2C2C2C',
      level2: '#333333',
      level3: '#404040',
      level4: '#4A4A4A',
      level5: '#545454',
    },
  },
}; 